console.log('📝 Satoshi Font Download Instructions:');
console.log('1. Visit https://www.fontshare.com/fonts/satoshi');
console.log('2. Download the "Satoshi" font package');
console.log('3. Extract the WOFF2 files from the package');
console.log('4. Place the following files in your public/fonts directory:');
console.log('   - Satoshi-Light.woff2');
console.log('   - Satoshi-Regular.woff2');
console.log('   - Satoshi-Medium.woff2');
console.log('   - Satoshi-Bold.woff2');
console.log('✅ Font setup complete!');
